// <auto-generated />
using System;
using CentralChamados.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CentralChamados.Persistence.Migrations
{
    [DbContext(typeof(ChamadosDbContext))]
    [Migration("20260925222528_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("CentralChamados.Domain.Chamado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Solicitante")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SolicitanteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Solucao")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tecnico")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TecnicoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SolicitanteId");

                    b.HasIndex("Status");

                    b.HasIndex("TecnicoId");

                    b.ToTable("Chamados", null, t =>
                        {
                            t.HasCheckConstraint("CK_Chamados_Descricao", "length(trim(Descricao)) BETWEEN 1 AND 2000");

                            t.HasCheckConstraint("CK_Chamados_Estado", "(Status = 'Aberto' AND TecnicoId IS NULL AND Tecnico IS NULL AND Solucao IS NULL) OR (Status = 'EmAtendimento' AND TecnicoId IS NOT NULL AND Tecnico IS NOT NULL AND Solucao IS NULL) OR (Status = 'Resolvido' AND TecnicoId IS NOT NULL AND Tecnico IS NOT NULL AND Solucao IS NOT NULL AND length(trim(Solucao)) BETWEEN 1 AND 2000)");

                            t.HasCheckConstraint("CK_Chamados_Titulo", "length(trim(Titulo)) BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("CentralChamados.Domain.EventoChamado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChamadoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2100)
                        .HasColumnType("TEXT");

                    b.Property<long>("Em")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequencia")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("ChamadoId", "Sequencia")
                        .IsUnique();

                    b.ToTable("Eventos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Eventos_Sequencia", "Sequencia >= 0");
                        });
                });

            modelBuilder.Entity("CentralChamados.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", null, t =>
                        {
                            t.HasCheckConstraint("CK_Usuarios_Nome", "length(trim(Nome)) BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("CentralChamados.Domain.Chamado", b =>
                {
                    b.HasOne("CentralChamados.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CentralChamados.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CentralChamados.Domain.EventoChamado", b =>
                {
                    b.HasOne("CentralChamados.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CentralChamados.Domain.Chamado", null)
                        .WithMany("Historico")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CentralChamados.Domain.Chamado", b =>
                {
                    b.Navigation("Historico");
                });
#pragma warning restore 612, 618
        }
    }
}
